services:
  vistashopverse_db:
    image: postgres:15-alpine
    container_name: vistashopverse_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${VSV_POSTGRES_DB}
      POSTGRES_USER: ${VSV_POSTGRES_USER}
      POSTGRES_PASSWORD: ${VSV_POSTGRES_PASSWORD}
    volumes:
      - vsv_postgres_data:/var/lib/postgresql/data
    ports:
      - "3003:5432"
    networks:
      - aa_network

  vistashopverse_app:
    container_name: vistashopverse_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: ${VSV_DATABASE_URL}
    restart: unless-stopped
    networks:
      - aa_network
    depends_on:
      - vistashopverse_db

networks:
  aa_network:
    driver: bridge

volumes:
  vsv_postgres_data:
