version: "3.8"

services:
  vistashopverse_db:
    image: postgres:15-alpine
    container_name: vistashopverse_db
    restart: always
    environment:
      POSTGRES_DB: ${VSV_POSTGRES_DB}
      POSTGRES_USER: ${VSV_POSTGRES_USER}
      POSTGRES_PASSWORD: ${VSV_POSTGRES_PASSWORD}
    volumes:
      - vsv_postgres_data:/var/lib/postgresql/data
    ports:
      - "3003:5432"
    networks:
      - vsv_network

  vistashopverse_app:
    build:
      context: ./projects/vistashopverse
      dockerfile: Dockerfile
    container_name: vistashopverse_app
    ports:
      - "3002:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: ${VSV_DATABASE_URL}
    depends_on:
      - vistashopverse_db
    networks:
      - vsv_network

networks:
  vsv_network:
    driver: bridge

volumes:
  vsv_postgres_data:
