name: Deploy Vistashopverse

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Lint the code
      - name: Lint
        run: npm run lint

      # Step 5: Build the project
      - name: Build the project
        run: npm run build

      # Step 6: Set up SSH access to the server
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 7: Deploy to the server
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no username@your-server-ip << 'EOF'
          cd /path/to/vistashopverse
          git pull origin main
          docker compose down
          docker compose build
          docker compose up -d
          EOF
