name: Deploy to Hetzner

on:
  push:
    branches:
      - main # or any branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Build Next.js project
        run: npm run build

      - name: Create artifact
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-build
          path: .next # This assumes your build output is in the .next folder

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: nextjs-build

      - name: Transfer files to Hetzner (SCP)
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USER }}
          key: ${{ secrets.HETZNER_PRIVATE_KEY }}
          port: 22
          source: ".next/*"
          target: "/path/to/deployment/directory" # Replace with your server path
